steps:
  - name: ':docker:'
    plugins:
      docker-compose#v1.5.2:
        build: loaders-gl
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber

  - wait

  - name: ':eslint:'
    command: 'yarn lint'
    plugins:
      docker-compose#v1.5.2:
        run: loaders-gl

  - name: ':node:'
    command: 'node test/start.js src'
    plugins:
      docker-compose#v1.5.2:
        run: loaders-gl

  - name: ':chrome:'
    command: 'sh /etc/init.d/xvfb && node test/start.js browser'
    plugins:
      docker-compose#v1.5.2:
        run: loaders-gl
